### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by wennie-tung**
－Name : Wennie
－URL : 
http://13.238.60.107:3000/
http://13.238.60.107:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Second separating line should be 1px height only.
2. There are some paddings around date input element.
3. Radio buttons should be larger with color the same as design.

**Comment by wennie-tung** [comment]
已修正！再麻煩老師～

－Name : Wennie
－URL :
http://13.238.60.107:3000/
http://13.238.60.107:3000/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
Second separating line should be 1px height only.

**Comment by wennie-tung** [comment]
感謝提醒，修正完畢

－Name : Wennie
－URL :
http://13.238.60.107:3000/
http://13.238.60.107:3000/attraction/10

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
