### PR TITLE
add week 1 assignment

### PR DESCRIPTION
**Pull request by wennie-tung**
Name : Wennie

API 位址 : 
http://13.238.60.107:3000/api/attractions?page=1
http://13.238.60.107:3000/api/attractions?page=0&keyword=劍潭
http://13.238.60.107:3000/api/attractions?page=0&keyword=北
http://13.238.60.107:3000/api/attraction/10
http://13.238.60.107:3000/api/mrts

### CODE REVIEW

**Comment by cwpeng** [comment]
You should request review so that I can review for you.

**Comment by wennie-tung** [comment]
> 您應該請求審核，以便我可以為您審核。

Sorry for didn't notice this detail. Thank you so much!

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. http://13.238.60.107:3000/api/attractions?page=0 should response something.
2. http://13.238.60.107:3000/api/attractions?page=1&keyword=%E5%8A%8D%E6%BD%AD should contain no data because there are no second page after filtering by 劍潭
3. http://13.238.60.107:3000/api/attractions?page=0&keyword=%E5%8C%97 should contain at most 12 attraction data.
4. http://13.238.60.107:3000/api/attractions?page=1&keyword=%E5%8C%97 should contain 3 attraction data because we will get 15 attraction data which break into 2 pages after filtering by 北.
5. Response format of http://13.238.60.107:3000/api/mrts is incorrect.

Fix issues and re-request review.

**Comment by wennie-tung** [comment]
完成修正上述錯誤，再麻煩老師協助 review，謝謝～
Name : Wennie

http://13.238.60.107:3000/api/attractions?page=0
http://13.238.60.107:3000/api/attractions?page=1&keyword=劍潭
http://13.238.60.107:3000/api/attractions?page=0&keyword=北
http://13.238.60.107:3000/api/attractions?page=1&keyword=北
http://13.238.60.107:3000/api/mrts

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
